"""
Django settings for blogSite project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Use Enviroment
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7x^j5tmnjr%_zcfpg*kw_l23^+j84p1@bqhq5(*7x@iuj!7rq*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authenticationApp',
    'social_django',
    'blogApp',
    'history',
    'ckeditor',
    'ckeditor_uploader',
    'admin_reorder',
    'widget_tweaks',
    'easy_thumbnails',
    'django_tagify',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'blogSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CKEDITOR CONFIG
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Undo', 'Redo'],
            ['FontSize', 'Bold', 'Italic', 'Underline',
                'Strike', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList'
                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image', 'Table', 'Iframe', 'Source'],
            ['Maximize'],
        ]
    },
}
CKEDITOR_UPLOAD_PATH = "uploads/"

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# AuthenticationApp
# Backend
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Basic Config
LOGIN_URL = 'authenticationApp:login'
LOGIN_REDIRECT_URL = 'blogApp:home'
LOGOUT_URL = 'authenticationApp:logout'
LOGOUT_REDIRECT_URL = 'authenticationApp:login'

SOCIAL_AUTH_URL_NAMESPACE = 'social-auth'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_POSTGRES_JSONFIELD = False

# Google Credential
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '605450426435-7a6r278rg3ufoij9moanbqq662o8u35h.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '4ElLLGngDD-P7gkVUEuYJ8zF'  # Client Secret

# Facebook Config
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id, name, email', }

# Facebook Credential
SOCIAL_AUTH_FACEBOOK_KEY = '169679231336038'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '07a3f90591ccaceaf57663acece61804'  # App Secret

# Mailjet
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'support@ske-blog.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = 'postmaster@sandboxf4818556e2a842b0b75dc6d975f2318f.mailgun.org'
EMAIL_HOST_PASSWORD = '1ef227964258c597f039114c05f63337-28d78af2-55ac59cd'
EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_PORT = '587'

# ADMIN SITE ORDER
ADMIN_REORDER = (
    'sites',

    {'app': 'blogApp', 'label': 'Banner',
     'models': ('blogApp.Banner',
                'blogApp.SponsorBanner',)
     },

    {'app': 'blogApp', 'label': 'Content',
     'models': ('blogApp.ContentSection',
                'blogApp.HasContent',
                'blogApp.Tag',
                'blogApp.HasTag',
                'blogApp.Post',)
     },

    {'app': 'authenticationApp', 'label': 'User',
     'models': ('authenticationApp.Profile',
                'auth.User',)
     },

    {'app': 'history', 'label': 'log',
     'models': ('history.History',
                'history.HistoryAdmin',)
     },
)

# Thumbnail
THUMBNAIL_ALIASES = {
    '': {
        'profile': {'size': (240, 240), 'crop': True},
        'articlecard': {'size': (250, 150), 'crop': True}
    },
}
